import { Text, XStack, YStack } from 'tamagui'

import templateStats from '@/docs/template-stats.json'

type Stat = {
  label: string
  value: string
  hint: string
}

/** OSS template metrics from docs/template-stats.json (generated by scripts/generate-template-stats.cjs). */
export function TemplateStatsCard() {
  const stats: Stat[] = [
    {
      label: 'Packed size',
      value: templateStats.packedLabel,
      hint: `npm pack · v${templateStats.version}`,
    },
    {
      label: 'Components',
      value: String(templateStats.componentTsxCount),
      hint: 'TSX under components/',
    },
    {
      label: 'Dashboard routes',
      value: String(templateStats.dashboardRouteCount),
      hint: `${templateStats.navHrefCount} nav links`,
    },
    {
      label: 'App screens',
      value: String(templateStats.appTsxCount),
      hint: 'TSX under app/',
    },
  ]

  return (
    <YStack
      rounded={16}
      borderWidth={1}
      borderColor="$borderColor"
      bg="$backgroundStrong"
      p={20}
      gap={16}
      width="100%"
      overflow="hidden"
    >
      <YStack gap={4}>
        <Text fontSize={18} fontWeight="600" color="$color">
          Template stats
        </Text>
        <Text fontSize={13} color="$gray10">
          Measured package metrics for this Verdant release (npm pack + file inventory).
        </Text>
      </YStack>

      <XStack flexWrap="wrap" gap={12} width="100%">
        {stats.map((s) => (
          <YStack
            key={s.label}
            flex={1}
            minW={140}
            rounded={12}
            borderWidth={1}
            borderColor="$borderColor"
            bg="$background"
            p={14}
            gap={6}
            overflow="hidden"
          >
            <Text fontSize={12} color="$gray10" numberOfLines={1}>
              {s.label}
            </Text>
            <Text fontSize={22} fontWeight="700" color="$color" letterSpacing={-0.3} numberOfLines={1}>
              {s.value}
            </Text>
            <Text fontSize={12} color="$gray10" numberOfLines={2}>
              {s.hint}
            </Text>
          </YStack>
        ))}
      </XStack>
    </YStack>
  )
}
